# Default values for bufstream-operator

# Install CRDs with the chart
installCRDs: true

replicaCount: 1

image:
  repository: bufstream-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Leader election configuration
leaderElection:
  enabled: true

# Health probe configuration
healthProbes:
  port: 8081
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
