apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bufstream-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bufstream-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bufstream-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "bufstream-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bufstream-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          command:
            - /manager
          args:
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect
            {{- end }}
            - --health-probe-bind-address=:{{ .Values.healthProbes.port }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports: []
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.healthProbes.port }}
            initialDelaySeconds: {{ .Values.healthProbes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthProbes.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.healthProbes.port }}
            initialDelaySeconds: {{ .Values.healthProbes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthProbes.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
