---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bufstream.buf.build
  resources:
  - acls
  - clusters
  - topics
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bufstream.buf.build
  resources:
  - acls/finalizers
  - clusters/finalizers
  - topics/finalizers
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - bufstream.buf.build
  resources:
  - acls/status
  - clusters/status
  - topics/status
  - users/status
  verbs:
  - get
  - patch
  - update
