# This rule is not used by the project bufstream-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bufstream-operator
    app.kubernetes.io/managed-by: kustomize
  name: topic-editor-role
rules:
- apiGroups:
  - bufstream.buf.build
  resources:
  - topics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bufstream.buf.build
  resources:
  - topics/status
  verbs:
  - get
