apiVersion: bufstream.buf.build/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: bufstream-operator
    app.kubernetes.io/managed-by: kustomize
  name: dev
spec:
  bootstrapServers: "bufstream.bufstream.svc.cluster.local:9092"
  # Reference to admin credentials for SASL authentication
  adminCredentialsRef:
    name: bufstream-admin-credentials
    namespace: bufstream
