apiVersion: bufstream.buf.build/v1alpha1
kind: Topic
metadata:
  labels:
    app.kubernetes.io/name: bufstream-operator
    app.kubernetes.io/managed-by: kustomize
  name: topic-sample
spec:
  bootstrapServers: "bufstream.bufstream.svc.cluster.local:9092"
  partitions: 3
  replicationFactor: 1
