apiVersion: bufstream.buf.build/v1alpha1
kind: BufstreamCluster
metadata:
  labels:
    app.kubernetes.io/name: bufstream-operator
    app.kubernetes.io/managed-by: kustomize
  name: bufstreamcluster-sample
spec:
  # TODO(user): Add fields here
